In [4]:
arquivo = open(r".\data\dom_casmurro.txt",encoding="utf-8")

texto = arquivo.read()
len(texto)

381375

In [5]:
palavras = texto.split()
len(palavras)

65707

In [7]:
import pandas as pd
tabela = pd.DataFrame({"palavras":palavras})
tabela

       palavras
0           DOM
1      CASMURRO
2           POR
3       MACHADO
4            DE
...         ...
65702         É
65703      bem,
65704         e
65705         o
65706    resto?

[65707 rows x 1 columns]

In [8]:
tabela["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?
65706    resto?            None

[65707 rows x 2 columns]

In [9]:
tabela = tabela.dropna()
tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65701   CXLVIII               É
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?

[65706 rows x 2 columns]

In [79]:
filtro = tabela ["palavras"] == "a"
tabela[filtro]

      palavras proxima_palavra
106          a         leitura
146          a           dizer
181          a        anecdota
207          a            casa
210          a           mesma
...        ...             ...
65110        a           minha
65177        a         theoria
65311        a         cabeça,
65402        a         virtude
65516        a            cara

[2258 rows x 2 columns]

In [80]:
tabela [filtro]["palavras"].value_counts()

palavras
a    2258
Name: count, dtype: int64

In [81]:
tabela [filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
minha           0.043401
nossa           0.012843
mesma           0.011072
um              0.009300
casa            0.008857
                  ...
principio,      0.000443
aroeira         0.000443
pitangueira,    0.000443
caçamba         0.000443
ramagem         0.000443
Name: proportion, Length: 1143, dtype: float64

In [82]:
tabela [filtro]["proxima_palavra"].value_counts().idxmax()

'minha'

In [ ]:
Print("Bentinho no dia seguinte entrou a minha")

In [54]:
palavras_mais_usadas = tabela ["palavras"].value_counts()

palavras_mais_usadas.head(15)

palavras
que     2519
a       2258
e       2001
de      1938
o       1527
não     1152
um       707
da       622
é        618
do       618
os       614
para     531
com      522
se       514
me       489
Name: count, dtype: int64